-- 20230630
-- 조건에 맞는 도서와 저자 리스트 출력하기
SELECT B.BOOK_ID, A.AUTHOR_NAME, DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') FROM BOOK B
INNER JOIN AUTHOR A ON A.AUTHOR_ID=B.AUTHOR_ID
WHERE B.CATEGORY LIKE '%경제%'
ORDER BY B.PUBLISHED_DATE;