-- 20230629
-- 저자 별 카테고리 별 매출액 집계하기
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((BS.SALES * B.PRICE)) AS TOTAL_SALES FROM BOOK AS B
INNER JOIN AUTHOR A ON A.AUTHOR_ID=B.AUTHOR_ID
INNER JOIN BOOK_SALES BS ON BS.BOOK_ID = B.BOOK_ID
WHERE YEAR(BS.SALES_DATE) ='2022' AND MONTH(BS.SALES_DATE)='01'
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;